// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://mqppmhlfjocudxrvshro.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xcHBtaGxmam9jdWR4cnZzaHJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM0MjUwMTIsImV4cCI6MjA0OTAwMTAxMn0.yX9uQ9ojKvI8SjqC7UOL8P4OfJUekc4XeI7ewQa0dEg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);